#############################################################################
# Makefile for building: rtrApp.app/Contents/MacOS/rtrApp
# Generated by qmake (3.1) (Qt 5.9.2)
# Project:  rtrApp.pro
# Template: app
# Command: /Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/bin/qmake -o Makefile rtrApp.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1y $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers -I../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers -I../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../Qt/5.9.2/clang_64/mkspecs/macx-clang -F/Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/lib
QMAKE         = /Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = rtrApp1.0.0
DISTDIR = /Users/kemal.doenmez/Entwicklung/beuth/rtr/.tmp/rtrApp1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		appwindow.cpp \
		camera.cpp \
		material/material.cpp \
		node.cpp \
		scene.cpp \
		geometry/cube.cpp \
		mesh/bbox.cpp \
		mesh/geometrybuffers.cpp \
		mesh/objloader.cpp \
		mesh/indexbuffer.cpp \
		mesh/mesh.cpp \
		rtrglwidget.cpp \
		navigator/nodenavigator.cpp \
		material/phong.cpp \
		navigator/position_navigator.cpp \
		navigator/rotate_y.cpp \
		material/toon.cpp \
		material/point.cpp qrc_models_and_textures.cpp \
		qrc_shaders.cpp \
		moc_appwindow.cpp \
		moc_rtrglwidget.cpp \
		moc_scene.cpp
OBJECTS       = main.o \
		appwindow.o \
		camera.o \
		material.o \
		node.o \
		scene.o \
		cube.o \
		bbox.o \
		geometrybuffers.o \
		objloader.o \
		indexbuffer.o \
		mesh.o \
		rtrglwidget.o \
		nodenavigator.o \
		phong.o \
		position_navigator.o \
		rotate_y.o \
		toon.o \
		point.o \
		qrc_models_and_textures.o \
		qrc_shaders.o \
		moc_appwindow.o \
		moc_rtrglwidget.o \
		moc_scene.o
DIST          = ../../Qt/5.9.2/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.9.2/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.9.2/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.9.2/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.9.2/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.9.2/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.9.2/clang_64/mkspecs/common/sanitize.conf \
		../../Qt/5.9.2/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.9.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.9.2/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.9.2/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.9.2/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.9.2/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.9.2/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.9.2/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/toolchain.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/file_copies.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/lex.prf \
		rtrApp.pro camera.h \
		appwindow.h \
		material/material.h \
		node.h \
		rtrglwidget.h \
		scene.h \
		geometry/cube.h \
		mesh/bbox.h \
		mesh/objloader.h \
		mesh/indexbuffer.h \
		mesh/mesh.h \
		mesh/vertexbuffer.h \
		mesh/geometrybuffers.h \
		navigator/nodenavigator.h \
		material/phong.h \
		navigator/position_navigator.h \
		navigator/rotate_y.h \
		material/toon.h \
		material/point.h main.cpp \
		appwindow.cpp \
		camera.cpp \
		material/material.cpp \
		node.cpp \
		scene.cpp \
		geometry/cube.cpp \
		mesh/bbox.cpp \
		mesh/geometrybuffers.cpp \
		mesh/objloader.cpp \
		mesh/indexbuffer.cpp \
		mesh/mesh.cpp \
		rtrglwidget.cpp \
		navigator/nodenavigator.cpp \
		material/phong.cpp \
		navigator/position_navigator.cpp \
		navigator/rotate_y.cpp \
		material/toon.cpp \
		material/point.cpp
QMAKE_TARGET  = rtrApp
DESTDIR       = 
TARGET        = rtrApp.app/Contents/MacOS/rtrApp

####### Custom Variables
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_VALID_ARCHS = x86_64
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET): ui_appwindow.h $(OBJECTS)  
	@test -d rtrApp.app/Contents/MacOS/ || mkdir -p rtrApp.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: rtrApp.pro ../../Qt/5.9.2/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt/5.9.2/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.9.2/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.9.2/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.9.2/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.9.2/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.9.2/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.9.2/clang_64/mkspecs/common/sanitize.conf \
		../../Qt/5.9.2/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.9.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.9.2/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.9.2/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.9.2/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.9.2/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.9.2/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.9.2/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.9.2/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/toolchain.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/file_copies.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.9.2/clang_64/mkspecs/features/lex.prf \
		rtrApp.pro \
		models_and_textures.qrc \
		shaders.qrc \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/QtGui.prl \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile rtrApp.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../Qt/5.9.2/clang_64/mkspecs/features/spec_pre.prf:
../../Qt/5.9.2/clang_64/mkspecs/qdevice.pri:
../../Qt/5.9.2/clang_64/mkspecs/features/device_config.prf:
../../Qt/5.9.2/clang_64/mkspecs/common/unix.conf:
../../Qt/5.9.2/clang_64/mkspecs/common/mac.conf:
../../Qt/5.9.2/clang_64/mkspecs/common/macx.conf:
../../Qt/5.9.2/clang_64/mkspecs/common/sanitize.conf:
../../Qt/5.9.2/clang_64/mkspecs/common/gcc-base.conf:
../../Qt/5.9.2/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt/5.9.2/clang_64/mkspecs/common/clang.conf:
../../Qt/5.9.2/clang_64/mkspecs/common/clang-mac.conf:
../../Qt/5.9.2/clang_64/mkspecs/qconfig.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.9.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.9.2/clang_64/mkspecs/features/qt_functions.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/qt_config.prf:
../../Qt/5.9.2/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt/5.9.2/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt/5.9.2/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/toolchain.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/mac/toolchain.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/default_pre.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/resolve_config.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/default_post.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/qml_debug.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/warn_on.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/qt.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/resources.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/moc.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/uic.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/unix/thread.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/qmake_use.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/file_copies.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/mac/rez.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/exceptions.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/yacc.prf:
../../Qt/5.9.2/clang_64/mkspecs/features/lex.prf:
rtrApp.pro:
models_and_textures.qrc:
shaders.qrc:
../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../Qt/5.9.2/clang_64/lib/QtGui.framework/QtGui.prl:
../../Qt/5.9.2/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile rtrApp.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

rtrApp.app/Contents/PkgInfo: 
	@test -d rtrApp.app/Contents || mkdir -p rtrApp.app/Contents
	@$(DEL_FILE) rtrApp.app/Contents/PkgInfo
	@echo "APPL????" > rtrApp.app/Contents/PkgInfo
rtrApp.app/Contents/Resources/empty.lproj: 
	@test -d rtrApp.app/Contents/Resources || mkdir -p rtrApp.app/Contents/Resources
	@touch rtrApp.app/Contents/Resources/empty.lproj
	
rtrApp.app/Contents/Info.plist: 
	@test -d rtrApp.app/Contents || mkdir -p rtrApp.app/Contents
	@$(DEL_FILE) rtrApp.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.rtrApp,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,rtrApp,g" -e "s,@LIBRARY@,rtrApp,g" -e "s,@TYPEINFO@,????,g" ../../Qt/5.9.2/clang_64/mkspecs/macx-clang/Info.plist.app >rtrApp.app/Contents/Info.plist

all: Makefile \
		rtrApp.app/Contents/PkgInfo \
		rtrApp.app/Contents/Resources/empty.lproj \
		rtrApp.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents models_and_textures.qrc shaders.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../Qt/5.9.2/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents camera.h appwindow.h material/material.h node.h rtrglwidget.h scene.h geometry/cube.h mesh/bbox.h mesh/objloader.h mesh/indexbuffer.h mesh/mesh.h mesh/vertexbuffer.h mesh/geometrybuffers.h navigator/nodenavigator.h material/phong.h navigator/position_navigator.h navigator/rotate_y.h material/toon.h material/point.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp appwindow.cpp camera.cpp material/material.cpp node.cpp scene.cpp geometry/cube.cpp mesh/bbox.cpp mesh/geometrybuffers.cpp mesh/objloader.cpp mesh/indexbuffer.cpp mesh/mesh.cpp rtrglwidget.cpp navigator/nodenavigator.cpp material/phong.cpp navigator/position_navigator.cpp navigator/rotate_y.cpp material/toon.cpp material/point.cpp $(DISTDIR)/
	$(COPY_FILE) --parents appwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r rtrApp.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

shaders: /Users/kemal.doenmez/Entwicklung/beuth/rtr/assets/shaders/phong.frag /Users/kemal.doenmez/Entwicklung/beuth/rtr/assets/shaders/phong.vert

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_models_and_textures.cpp qrc_shaders.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_models_and_textures.cpp qrc_shaders.cpp
qrc_models_and_textures.cpp: models_and_textures.qrc \
		../../Qt/5.9.2/clang_64/bin/rcc \
		models/goblin.obj \
		models/duck/duck.obj \
		models/obiwan/obiwan.obj \
		models/stuff/alien.obj \
		models/stuff/F117_H.obj \
		models/extern/venus.obj \
		models/extern/dragon.obj \
		models/extern/buddha.obj \
		models/extern/sphere.obj \
		models/teapot/teapot.obj \
		textures/RTR-ist-super-4-3.png
	/Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/bin/rcc -name models_and_textures models_and_textures.qrc -o qrc_models_and_textures.cpp

qrc_shaders.cpp: shaders.qrc \
		../../Qt/5.9.2/clang_64/bin/rcc \
		shaders/phong.frag \
		shaders/obiwan.vert \
		shaders/toon.frag \
		shaders/texture.vert \
		shaders/point.frag \
		shaders/phong.vert \
		shaders/obiwan.frag \
		shaders/toon.vert \
		shaders/texture.frag \
		shaders/point.vert
	/Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/bin/rcc -name shaders shaders.qrc -o qrc_shaders.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Qt/5.9.2/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++1y $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -dM -E -o moc_predefs.h ../../Qt/5.9.2/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_appwindow.cpp moc_rtrglwidget.cpp moc_scene.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_appwindow.cpp moc_rtrglwidget.cpp moc_scene.cpp
moc_appwindow.cpp: ../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		scene.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLVertexArrayObject \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLFramebufferObject \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		node.h \
		mesh/mesh.h \
		mesh/geometrybuffers.h \
		mesh/vertexbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		mesh/indexbuffer.h \
		mesh/bbox.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		material/material.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLContext \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		camera.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QMatrix4x4 \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		material/phong.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLTexture \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		material/toon.h \
		material/point.h \
		navigator/rotate_y.h \
		navigator/nodenavigator.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		appwindow.h \
		moc_predefs.h \
		../../Qt/5.9.2/clang_64/bin/moc
	/Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/mkspecs/macx-clang -I/Users/kemal.doenmez/Entwicklung/beuth/rtr -I/Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/lib/QtGui.framework/Headers -I/Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -F/Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/lib appwindow.h -o moc_appwindow.cpp

moc_rtrglwidget.cpp: ../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLDebugLogger \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopengldebug.h \
		rtrglwidget.h \
		moc_predefs.h \
		../../Qt/5.9.2/clang_64/bin/moc
	/Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/mkspecs/macx-clang -I/Users/kemal.doenmez/Entwicklung/beuth/rtr -I/Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/lib/QtGui.framework/Headers -I/Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -F/Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/lib rtrglwidget.h -o moc_rtrglwidget.cpp

moc_scene.cpp: ../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLVertexArrayObject \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLFramebufferObject \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		node.h \
		mesh/mesh.h \
		mesh/geometrybuffers.h \
		mesh/vertexbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		mesh/indexbuffer.h \
		mesh/bbox.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		material/material.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLContext \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		camera.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QMatrix4x4 \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		material/phong.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLTexture \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		material/toon.h \
		material/point.h \
		navigator/rotate_y.h \
		navigator/nodenavigator.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		scene.h \
		moc_predefs.h \
		../../Qt/5.9.2/clang_64/bin/moc
	/Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/mkspecs/macx-clang -I/Users/kemal.doenmez/Entwicklung/beuth/rtr -I/Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/lib/QtGui.framework/Headers -I/Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/lib/QtCore.framework/Headers -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -F/Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/lib scene.h -o moc_scene.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_appwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_appwindow.h
ui_appwindow.h: appwindow.ui \
		../../Qt/5.9.2/clang_64/bin/uic \
		rtrglwidget.h \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLDebugLogger \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopengldebug.h
	/Users/kemal.doenmez/Entwicklung/Qt/5.9.2/clang_64/bin/uic appwindow.ui -o ui_appwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QSurfaceFormat \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h \
		appwindow.h \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		scene.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLVertexArrayObject \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLFramebufferObject \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		node.h \
		mesh/mesh.h \
		mesh/geometrybuffers.h \
		mesh/vertexbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		mesh/indexbuffer.h \
		mesh/bbox.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		material/material.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLContext \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		camera.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QMatrix4x4 \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		material/phong.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLTexture \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		material/toon.h \
		material/point.h \
		navigator/rotate_y.h \
		navigator/nodenavigator.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QMouseEvent
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

appwindow.o: appwindow.cpp ../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/QDesktopWidget \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		appwindow.h \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		scene.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLVertexArrayObject \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLFramebufferObject \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		node.h \
		mesh/mesh.h \
		mesh/geometrybuffers.h \
		mesh/vertexbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		mesh/indexbuffer.h \
		mesh/bbox.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		material/material.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLContext \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		camera.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QMatrix4x4 \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		material/phong.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLTexture \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		material/toon.h \
		material/point.h \
		navigator/rotate_y.h \
		navigator/nodenavigator.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		ui_appwindow.h \
		rtrglwidget.h \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLDebugLogger \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopengldebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o appwindow.o appwindow.cpp

camera.o: camera.cpp camera.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QMatrix4x4 \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		material/material.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o camera.cpp

material.o: material/material.cpp material/material.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o material.o material/material.cpp

node.o: node.cpp node.h \
		mesh/mesh.h \
		mesh/geometrybuffers.h \
		mesh/vertexbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		mesh/indexbuffer.h \
		mesh/bbox.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		material/material.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLVertexArrayObject \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLContext \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		camera.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QMatrix4x4 \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o node.o node.cpp

scene.o: scene.cpp scene.h \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLVertexArrayObject \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLFramebufferObject \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		node.h \
		mesh/mesh.h \
		mesh/geometrybuffers.h \
		mesh/vertexbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		mesh/indexbuffer.h \
		mesh/bbox.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		material/material.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLContext \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		camera.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QMatrix4x4 \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		material/phong.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLTexture \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		material/toon.h \
		material/point.h \
		navigator/rotate_y.h \
		navigator/nodenavigator.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		geometry/cube.h \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QtMath \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qmath.h \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scene.o scene.cpp

cube.o: geometry/cube.cpp geometry/cube.h \
		mesh/geometrybuffers.h \
		mesh/vertexbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		mesh/indexbuffer.h \
		mesh/bbox.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		material/material.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLVertexArrayObject \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLContext \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cube.o geometry/cube.cpp

bbox.o: mesh/bbox.cpp mesh/bbox.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bbox.o mesh/bbox.cpp

geometrybuffers.o: mesh/geometrybuffers.cpp mesh/geometrybuffers.h \
		mesh/vertexbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		mesh/indexbuffer.h \
		mesh/bbox.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		material/material.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLVertexArrayObject \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLContext \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		mesh/objloader.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QVector4D \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qvector4d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o geometrybuffers.o mesh/geometrybuffers.cpp

objloader.o: mesh/objloader.cpp mesh/objloader.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QVector4D \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qvector4d.h \
		mesh/bbox.h \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QVector \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QHash \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qhash.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objloader.o mesh/objloader.cpp

indexbuffer.o: mesh/indexbuffer.cpp mesh/indexbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o indexbuffer.o mesh/indexbuffer.cpp

mesh.o: mesh/mesh.cpp mesh/mesh.h \
		mesh/geometrybuffers.h \
		mesh/vertexbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		mesh/indexbuffer.h \
		mesh/bbox.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		material/material.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLVertexArrayObject \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLContext \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		mesh/objloader.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QVector4D \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qvector4d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mesh.o mesh/mesh.cpp

rtrglwidget.o: rtrglwidget.cpp rtrglwidget.h \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLDebugLogger \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopengldebug.h \
		scene.h \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.9.2/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLVertexArrayObject \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLFramebufferObject \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		node.h \
		mesh/mesh.h \
		mesh/geometrybuffers.h \
		mesh/vertexbuffer.h \
		mesh/indexbuffer.h \
		mesh/bbox.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		material/material.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLContext \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		camera.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QMatrix4x4 \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		material/phong.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLTexture \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		material/toon.h \
		material/point.h \
		navigator/rotate_y.h \
		navigator/nodenavigator.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QMouseEvent
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rtrglwidget.o rtrglwidget.cpp

nodenavigator.o: navigator/nodenavigator.cpp navigator/nodenavigator.h \
		node.h \
		mesh/mesh.h \
		mesh/geometrybuffers.h \
		mesh/vertexbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		mesh/indexbuffer.h \
		mesh/bbox.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		material/material.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLVertexArrayObject \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLContext \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		camera.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QMatrix4x4 \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QMouseEvent
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nodenavigator.o navigator/nodenavigator.cpp

phong.o: material/phong.cpp material/phong.h \
		material/material.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLTexture \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopengltexture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o phong.o material/phong.cpp

position_navigator.o: navigator/position_navigator.cpp navigator/position_navigator.h \
		navigator/nodenavigator.h \
		node.h \
		mesh/mesh.h \
		mesh/geometrybuffers.h \
		mesh/vertexbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		mesh/indexbuffer.h \
		mesh/bbox.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		material/material.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLVertexArrayObject \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLContext \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		camera.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QMatrix4x4 \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QtMath \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qmath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o position_navigator.o navigator/position_navigator.cpp

rotate_y.o: navigator/rotate_y.cpp navigator/rotate_y.h \
		navigator/nodenavigator.h \
		node.h \
		mesh/mesh.h \
		mesh/geometrybuffers.h \
		mesh/vertexbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLBuffer \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		mesh/indexbuffer.h \
		mesh/bbox.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QVector3D \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		material/material.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLVertexArrayObject \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLContext \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		camera.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QMatrix4x4 \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/QtMath \
		../../Qt/5.9.2/clang_64/lib/QtCore.framework/Headers/qmath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rotate_y.o navigator/rotate_y.cpp

toon.o: material/toon.cpp material/toon.h \
		material/material.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		material/phong.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLTexture \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopengltexture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o toon.o material/toon.cpp

point.o: material/point.cpp material/point.h \
		material/material.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLShaderProgram \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		material/phong.h \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/QOpenGLTexture \
		../../Qt/5.9.2/clang_64/lib/QtGui.framework/Headers/qopengltexture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o point.o material/point.cpp

qrc_models_and_textures.o: qrc_models_and_textures.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_models_and_textures.o qrc_models_and_textures.cpp

qrc_shaders.o: qrc_shaders.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_shaders.o qrc_shaders.cpp

moc_appwindow.o: moc_appwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_appwindow.o moc_appwindow.cpp

moc_rtrglwidget.o: moc_rtrglwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rtrglwidget.o moc_rtrglwidget.cpp

moc_scene.o: moc_scene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scene.o moc_scene.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

